export default function handler(req,res){
  const html=`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>P14 · High Fidelity UI Gallery</title>
<style>
:root{--bg:#ececf1;--card:#fff;--ink:#111113;--muted:#77777e;--line:#e9e9ed;--blue:#0a84ff;--violet:#7c5ce7;--orange:#f59d18;--red:#e94747;--green:#2fa36b}
*{box-sizing:border-box}html,body{margin:0;background:linear-gradient(180deg,#f6f6f8,#e6e6eb);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","PingFang SC",sans-serif;color:var(--ink)}
main{max-width:1460px;margin:auto;padding:92px 30px 72px}.hero{max-width:900px;margin:0 auto 42px;text-align:center}.eyebrow{font-size:12px;font-weight:750;letter-spacing:.12em;color:#777;text-transform:uppercase}.hero h1{font-size:34px;letter-spacing:-.8px;margin:8px 0 10px}.hero p{margin:0;color:#717178;line-height:1.55;font-size:15px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(315px,1fr));gap:34px 24px;align-items:start}.shot{display:flex;flex-direction:column;align-items:center}.cap{width:100%;max-width:350px;margin:0 auto 12px}.cap b{display:block;font-size:15px}.cap span{display:block;color:#7c7c83;font-size:12px;margin-top:3px}.phone{width:350px;height:758px;background:#f2f2f7;border:7px solid #18181a;border-radius:46px;overflow:hidden;box-shadow:0 24px 70px rgba(0,0,0,.16);position:relative}.island{position:absolute;z-index:8;top:10px;left:50%;transform:translateX(-50%);width:104px;height:29px;background:#0d0d0e;border-radius:17px}.status{height:50px;padding:14px 22px 0;font-size:12px;font-weight:700;display:flex;justify-content:space-between;position:relative;z-index:3}.nav{padding:10px 18px 10px;display:flex;align-items:center;justify-content:space-between}.nav h2{font-size:31px;letter-spacing:-.8px;margin:0}.dots{font-size:22px;letter-spacing:2px}.screen{height:100%;display:flex;flex-direction:column}.content{padding:0 12px 120px;overflow:hidden}.rows{display:flex;flex-direction:column;gap:8px}.row{background:rgba(255,255,255,.88);border-radius:18px;padding:13px 12px;display:grid;grid-template-columns:25px 1fr 26px;gap:8px;box-shadow:0 1px 0 rgba(0,0,0,.025)}.circle{width:22px;height:22px;border:2px solid #c6c6cb;border-radius:50%}.body{font-size:15px;line-height:1.35}.meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.pill{font-size:10.5px;padding:4px 6px;border-radius:7px;background:#ededf2;color:#626269}.pill.p{background:#e9f3ff;color:#1765b2}.pill.a{background:#f1eaff;color:#6f3ed0}.pill.t{background:#fff1d8;color:#955900}.sync{font-size:11px;color:#929299;font-weight:800;letter-spacing:-1px}.bottom{position:absolute;left:0;right:0;bottom:0;height:103px;background:linear-gradient(to top,#f2f2f7 70%,rgba(242,242,247,.4),transparent)}.tabs{position:absolute;left:50%;bottom:15px;transform:translateX(-50%);width:224px;height:50px;border-radius:18px;background:rgba(255,255,255,.88);display:grid;grid-template-columns:1fr 1fr;padding:4px;box-shadow:0 8px 26px rgba(0,0,0,.07)}.tab{display:grid;place-items:center;color:#85858c;font-size:13px;font-weight:700;border-radius:14px}.tab.on{background:white;color:#111;box-shadow:0 2px 9px rgba(0,0,0,.07)}.plus{position:absolute;right:18px;bottom:82px;width:50px;height:50px;border-radius:50%;background:#111;color:#fff;display:grid;place-items:center;font-size:29px;box-shadow:0 8px 22px rgba(0,0,0,.2)}
.sheetbg{position:absolute;inset:0;background:rgba(0,0,0,.13)}.sheet{position:absolute;left:0;right:0;bottom:0;min-height:470px;background:rgba(251,251,253,.99);border-radius:30px 30px 0 0;padding:11px 16px 24px;box-shadow:0 -18px 55px rgba(0,0,0,.14)}.grab{width:37px;height:5px;background:#d0d0d5;border-radius:3px;margin:0 auto 17px}.edit{min-height:130px;background:#fff;border:1px solid #ececf0;border-radius:18px;padding:15px;font-size:17px;line-height:1.4}.muted{color:#8c8c93}.toolrow{display:flex;justify-content:space-between;align-items:center;margin:14px 3px}.tools{display:flex;gap:7px}.tool{padding:7px 9px;border-radius:11px;background:#ececf1;color:#555;font-size:12px}.record{display:flex;align-items:center;gap:12px}.mic{width:66px;height:66px;border-radius:50%;background:#ff453a;color:white;display:grid;place-items:center;font-size:24px;box-shadow:0 0 0 9px rgba(255,69,58,.1)}.wave{height:36px;display:flex;gap:3px;align-items:center}.wave i{width:3px;border-radius:3px;background:#ff453a}.wave i:nth-child(1){height:12px}.wave i:nth-child(2){height:29px}.wave i:nth-child(3){height:19px}.wave i:nth-child(4){height:34px}.wave i:nth-child(5){height:15px}.wave i:nth-child(6){height:24px}.wave i:nth-child(7){height:31px}.wave i:nth-child(8){height:17px}.live{font-size:12px;color:#d54040;font-weight:700;margin-left:auto}.actions{display:flex;justify-content:space-between;align-items:center;margin-top:16px}.save{padding:10px 16px;border-radius:13px;background:#111;color:white;font-weight:750;font-size:13px}.cancel{font-size:13px;color:#777}
.aihalo{position:absolute;inset:175px 25px auto;height:150px;border-radius:30px;background:radial-gradient(circle at 50% 50%,rgba(124,92,231,.14),rgba(10,132,255,.04) 45%,transparent 72%);filter:blur(7px)}.processing{display:flex;gap:7px;align-items:center;color:#7050ca;font-size:12px;font-weight:700}.spark{width:23px;height:23px;border-radius:50%;background:#eee7ff;display:grid;place-items:center}.ghost{opacity:.34;text-decoration:line-through}.proposal{margin-top:10px;font-size:18px;line-height:1.45;font-weight:530}.detail{padding:0 17px 120px}.detailCard{background:white;border-radius:21px;padding:18px 16px}.detailBody{font-size:21px;line-height:1.38;letter-spacing:-.25px}.section{margin-top:20px}.label{font-size:11px;color:#8e8e95;text-transform:uppercase;letter-spacing:.08em;font-weight:750;margin-bottom:7px}.audio{height:58px;border-radius:15px;background:#f3f3f6;padding:10px 12px;display:flex;align-items:center;gap:10px}.play{width:33px;height:33px;border-radius:50%;background:#111;color:white;display:grid;place-items:center}.bars{flex:1;height:23px;background:repeating-linear-gradient(90deg,#a9a9b0 0 2px,transparent 2px 6px);opacity:.65}.searchbox{margin:2px 16px 12px;background:#e4e4e9;border-radius:12px;padding:10px 12px;color:#76767d;font-size:14px}.filter{display:flex;gap:6px;padding:0 16px 10px;overflow:hidden}.chip{white-space:nowrap;padding:6px 9px;border-radius:10px;background:#fff;font-size:11px;color:#5f5f65}.chip.on{background:#111;color:#fff}.banner{margin:0 12px 10px;padding:10px 12px;border-radius:13px;background:#fff0ef;color:#a03d38;font-size:12px;display:flex;justify-content:space-between}.offline{margin:0 12px 10px;padding:10px 12px;border-radius:13px;background:#f3f0ff;color:#684ac1;font-size:12px}.checkdone{width:22px;height:22px;border-radius:50%;background:#0a84ff;color:white;display:grid;place-items:center;font-size:12px;font-weight:800}.strike{color:#6f6f75}.toast{position:absolute;left:50%;bottom:118px;transform:translateX(-50%);background:rgba(25,25,27,.94);color:#fff;padding:10px 13px;border-radius:13px;font-size:12px;white-space:nowrap}.toast b{color:#6bb6ff;margin-left:10px}.scan{height:2px;background:linear-gradient(90deg,transparent,#7c5ce7,#0a84ff,transparent);margin:13px 0;box-shadow:0 0 18px rgba(124,92,231,.35)}
@media(max-width:650px){main{padding:78px 12px 50px}.hero h1{font-size:28px}.grid{grid-template-columns:1fr;gap:40px}.phone{width:min(350px,94vw)}}
</style></head><body><main>
<div class="hero"><div class="eyebrow">P14 · R1@r4 · Visual Baseline</div><h1>高保真移动端 UI 图册</h1><p>这一组是视觉基准，不承担交互逻辑。交互、异常分支与状态切换请切回“交互预览”；两者一起作为设计评审证据。</p></div>
<div class="grid">

<div class="shot"><div class="cap"><b>01 · 收集箱</b><span>默认首页 / 未完成 Entry / 安静的同步状态</span></div><div class="phone"><div class="island"></div><div class="screen"><div class="status"><span>9:41</span><span>●●● Wi‑Fi ▰</span></div><div class="nav"><h2>收集箱</h2><div class="dots">•••</div></div><div class="content"><div class="rows">
<div class="row"><div class="circle"></div><div><div class="body">明天处理 P14 同步问题</div><div class="meta"><span class="pill p">P14</span><span class="pill t">明天 20:00</span><span class="pill a">✦ 开发</span></div></div><div class="sync">✓✓</div></div>
<div class="row"><div class="circle"></div><div><div class="body">去年的长崎旅行，最想念的是生物公园里的卡皮巴拉。</div><div class="meta"><span class="pill a">✦ 旅行感悟</span><span class="pill">图片 3</span></div></div><div class="sync">✓</div></div>
<div class="row"><div class="circle"></div><div><div class="body">整理 Gmail 历史邮件导入方案</div><div class="meta"><span class="pill p">AIBOX</span><span class="pill">语音 0:24</span></div></div><div class="sync">✓✓</div></div>
</div></div><div class="plus">+</div><div class="bottom"><div class="tabs"><div class="tab on">收集箱</div><div class="tab">已完成</div></div></div></div></div></div>

<div class="shot"><div class="cap"><b>02 · 按住说</b><span>Live Transcript / 强录音反馈 / 不进入全屏</span></div><div class="phone"><div class="island"></div><div class="screen"><div class="status"><span>9:41</span><span>●●● Wi‑Fi ▰</span></div><div class="nav"><h2>收集箱</h2><div class="dots">•••</div></div><div class="sheetbg"></div><div class="sheet"><div class="grab"></div><div class="edit">那个 P14 吧，我觉得明天还是要把那个同步的问题弄一下<span style="color:#aaa">…</span></div><div class="toolrow"><div class="tools"><span class="tool">▧ 照片</span><span class="tool">＋ 文件</span></div><span class="live">正在听写</span></div><div class="record"><div class="mic">◉</div><div class="wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="muted" style="font-size:12px">松开结束</div></div><div class="actions"><span class="cancel">取消</span><span class="save" style="opacity:.28">保存</span></div></div></div></div></div>

<div class="shot"><div class="cap"><b>03 · AI 整理中</b><span>松手后锁定编辑 / 无通用 spinner / 轻量扫描感</span></div><div class="phone"><div class="island"></div><div class="screen"><div class="status"><span>9:41</span><span>●●● Wi‑Fi ▰</span></div><div class="nav"><h2>收集箱</h2><div class="dots">•••</div></div><div class="sheetbg"></div><div class="aihalo"></div><div class="sheet"><div class="grab"></div><div class="processing"><span class="spark">✦</span>正在整理</div><div class="edit" style="margin-top:10px"><span class="ghost">那个 P14 吧，我觉得</span> 明天还是要把那个同步的问题弄一下</div><div class="scan"></div><div class="muted" style="font-size:12px;line-height:1.5">正在识别时间、项目和可复用标签。原始录音已经安全保存在本机。</div><div class="actions"><span class="cancel" style="opacity:.35">取消</span><span class="save" style="opacity:.28">保存</span></div></div></div></div></div>

<div class="shot"><div class="cap"><b>04 · 最终提案</b><span>AI 直接给结果 / 用户可改 / 明确保存</span></div><div class="phone"><div class="island"></div><div class="screen"><div class="status"><span>9:41</span><span>●●● Wi‑Fi ▰</span></div><div class="nav"><h2>收集箱</h2><div class="dots">•••</div></div><div class="sheetbg"></div><div class="sheet"><div class="grab"></div><div style="font-size:12px;color:#777;text-align:center;margin-bottom:8px">AI 已整理 · 尚未保存</div><div class="edit"><div class="proposal">明天处理 P14 同步问题</div></div><div class="meta" style="margin:11px 2px 0"><span class="pill p">P14</span><span class="pill t">明天 20:00</span><span class="pill a">✦ 开发</span></div><div class="toolrow"><div class="tools"><span class="tool">🎙 0:11</span><span class="tool">＋ 继续录音</span></div><span style="font-size:12px;color:#7050ca">✦ 已整理</span></div><div class="actions"><span class="cancel">取消</span><span class="save">保存</span></div></div></div></div></div>

<div class="shot"><div class="cap"><b>05 · Entry 详情</b><span>正文优先 / 元数据退后 / 多段音频作为证据</span></div><div class="phone"><div class="island"></div><div class="screen"><div class="status"><span>9:41</span><span>●●● Wi‑Fi ▰</span></div><div class="nav"><div style="font-size:20px">‹</div><div style="font-size:16px;font-weight:720">Entry</div><div class="dots">•••</div></div><div class="detail"><div class="detailCard"><div class="detailBody">明天处理 P14 同步问题</div><div class="meta"><span class="pill p">P14</span><span class="pill t">明天 20:00</span><span class="pill a">✦ 开发</span></div><div class="section"><div class="label">录音</div><div class="audio"><div class="play">▶</div><div class="bars"></div><span style="font-size:11px;color:#777">0:11</span></div><div class="audio" style="margin-top:7px"><div class="play">▶</div><div class="bars"></div><span style="font-size:11px;color:#777">0:18</span></div></div><div class="section"><div class="label">提醒</div><div style="font-size:14px">9 月 4 日 20:00</div></div><div class="section"><div class="label">同步</div><div style="font-size:13px;color:#666">✓✓ 已同步到服务器</div></div></div></div></div></div></div>

<div class="shot"><div class="cap"><b>06 · 已完成 + 撤销</b><span>完成立即退出 Inbox / 底部非模态 Undo</span></div><div class="phone"><div class="island"></div><div class="screen"><div class="status"><span>9:41</span><span>●●● Wi‑Fi ▰</span></div><div class="nav"><h2>已完成</h2><div class="dots">•••</div></div><div class="content"><div class="rows"><div class="row"><div class="checkdone">✓</div><div><div class="body strike">整理 QQ 邮箱拉取程序</div><div class="meta"><span class="pill p">P2</span><span class="pill">今天 16:28</span></div></div><div class="sync">✓✓</div></div><div class="row"><div class="checkdone">✓</div><div><div class="body strike">确认 P18 iPhone AI 测试结论</div><div class="meta"><span class="pill p">P18</span></div></div><div class="sync">✓✓</div></div></div></div><div class="toast">已完成 <b>撤销</b></div><div class="bottom"><div class="tabs"><div class="tab">收集箱</div><div class="tab on">已完成</div></div></div></div></div></div>

<div class="shot"><div class="cap"><b>07 · 下拉搜索</b><span>不占一级导航 / 搜未完成 + 已完成 / 轻筛选</span></div><div class="phone"><div class="island"></div><div class="screen"><div class="status"><span>9:41</span><span>●●● Wi‑Fi ▰</span></div><div class="nav"><h2>收集箱</h2><div class="dots">•••</div></div><div class="searchbox">⌕ P14</div><div class="filter"><span class="chip on">全部</span><span class="chip">未完成</span><span class="chip">已完成</span><span class="chip">有附件</span></div><div class="content" style="padding-top:0"><div class="rows"><div class="row"><div class="circle"></div><div><div class="body">明天处理 P14 同步问题</div><div class="meta"><span class="pill p">P14</span><span class="pill t">明天 20:00</span></div></div><div class="sync">✓✓</div></div><div class="row"><div class="checkdone">✓</div><div><div class="body strike">重做 P14 导航结构</div><div class="meta"><span class="pill p">P14</span><span class="pill">已完成</span></div></div><div class="sync">✓✓</div></div></div></div></div></div></div>

<div class="shot"><div class="cap"><b>08 · 离线 / 同步失败</b><span>本地保存不受阻 / 网络失败不制造红色焦虑</span></div><div class="phone"><div class="island"></div><div class="screen"><div class="status"><span>9:41</span><span>●●● ︎○ ▰</span></div><div class="nav"><h2>收集箱</h2><div class="dots">•••</div></div><div class="offline">当前离线 · 新 Entry 会继续保存在本机，联网后自动同步</div><div class="banner"><span>1 条同步暂未成功</span><span>查看 ›</span></div><div class="content" style="padding-top:0"><div class="rows"><div class="row"><div class="circle"></div><div><div class="body">测试离线时 P14 新建 Entry</div><div class="meta"><span class="pill p">P14</span><span class="pill">仅本机</span></div></div><div class="sync">✓</div></div><div class="row"><div class="circle"></div><div><div class="body">附件上传失败时仍允许继续编辑</div><div class="meta"><span class="pill">图片 2</span><span class="pill" style="background:#fff0ef;color:#a23d38">待重试</span></div></div><div class="sync" style="color:#b16a62;letter-spacing:0">!</div></div></div></div><div class="plus">+</div><div class="bottom"><div class="tabs"><div class="tab on">收集箱</div><div class="tab">已完成</div></div></div></div></div></div>

</div></main></body></html>`;
  res.setHeader('Content-Type','text/html; charset=utf-8');
  res.setHeader('Cache-Control','no-store');
  res.status(200).send(html);
}
