export default function handler(req,res){
  res.setHeader('Content-Type','text/html; charset=utf-8');
  res.setHeader('Cache-Control','no-store');
  res.status(200).send(`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>P14 Semantic Motion v3</title>
<style>
:root{--bg:#07080d;--panel:#11131b;--text:#f8f8fb;--muted:#9398a7;--hair:rgba(255,255,255,.085);--blue:#66adff;--violet:#a681ff;--amber:#ffc66d;--red:#ff6670;--ease:cubic-bezier(.22,.8,.2,1);--easeout:cubic-bezier(.2,.75,.25,1)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","PingFang SC",sans-serif;background:radial-gradient(circle at 50% 0,#16192a 0,#090a11 40%,#07080d 75%);color:var(--text)}
body{overflow:hidden}.wrap{min-height:100vh;display:grid;place-items:center;padding:28px}.phone{width:min(430px,94vw);height:min(890px,94vh);border-radius:46px;overflow:hidden;position:relative;background:linear-gradient(180deg,#10121b,#090a10);box-shadow:0 42px 110px rgba(0,0,0,.56),inset 0 0 0 1px rgba(255,255,255,.08)}
.ambient{position:absolute;inset:-25%;background:conic-gradient(from 20deg,transparent 0 23%,rgba(102,173,255,.10),transparent 36% 58%,rgba(166,129,255,.10),transparent 72%);filter:blur(44px);animation:ambient 12s linear infinite}.status,.head,.editor,.bottom,.replay{position:relative;z-index:2}.status{height:50px;padding:18px 24px 0;display:flex;justify-content:space-between;font-size:13px;color:#e9ebf3}.head{padding:20px 22px 14px}.head h1{margin:0;font-size:31px;letter-spacing:-.7px}.head p{margin:6px 0 0;color:var(--muted);font-size:13px}
.editor{margin:14px 16px 0;height:470px;border-radius:30px;padding:25px 22px;background:linear-gradient(180deg,rgba(255,255,255,.08),rgba(255,255,255,.045));box-shadow:inset 0 0 0 1px var(--hair),0 25px 60px rgba(0,0,0,.22);overflow:hidden}.editor:before{content:"";position:absolute;inset:-1px;border-radius:31px;padding:1px;background:linear-gradient(115deg,transparent 8%,var(--blue),#c9e5ff 38%,var(--violet) 58%,transparent 90%);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;opacity:0;transition:opacity .22s}.phone.ai .editor:before{opacity:.9;animation:borderDrift 1.5s ease-in-out infinite alternate}
.raw{font-size:21px;line-height:1.65;letter-spacing:-.2px;min-height:112px}.token{display:inline-block;white-space:pre;vertical-align:baseline;position:relative;overflow:visible}.token.semantic{border-radius:6px}.phone.parse .token.semantic{animation:semanticPulse .42s var(--ease) both}.phone.parse .token.project{color:#b9d9ff;text-shadow:0 0 14px rgba(102,173,255,.38)}.phone.parse .token.time{color:#ffe0a5;text-shadow:0 0 14px rgba(255,198,109,.3)}.phone.parse .token.core{color:#ddd5ff;text-shadow:0 0 13px rgba(166,129,255,.3)}
.ai-label{height:28px;margin-top:18px;color:#cbbaff;font-size:13px;opacity:0;display:flex;align-items:center;gap:7px;transition:opacity .2s}.phone.ai .ai-label{opacity:1}.spark{width:16px;height:16px;display:grid;place-items:center;filter:drop-shadow(0 0 12px #a681ff);animation:spark 1.1s ease-in-out infinite}
.finalrow{margin-top:12px;min-height:60px;font-size:25px;font-weight:720;letter-spacing:-.45px;display:flex;align-items:flex-start;gap:0;opacity:0;transform:translateY(5px);transition:opacity .22s,transform .3s var(--ease)}.phone.final .finalrow{opacity:1;transform:none}.actionword{opacity:0;transform:translateY(5px);filter:blur(5px)}.phone.final .actionword{animation:formWord .28s .04s var(--ease) forwards}.core-final{opacity:0}.phone.final .core-final{animation:coreIn .26s .09s var(--ease) forwards}
.chipzone{position:absolute;left:22px;right:22px;bottom:28px}.chiptitle{font-size:11px;color:#727888;margin-bottom:8px;text-transform:uppercase;letter-spacing:.7px}.chips{display:flex;gap:8px;flex-wrap:wrap;min-height:38px}.chip{visibility:hidden;opacity:0;padding:9px 12px;border-radius:12px;font-size:12px;font-weight:650;background:rgba(255,255,255,.06);box-shadow:inset 0 0 0 1px rgba(255,255,255,.08)}.chip.project{color:#93c8ff;background:rgba(59,133,220,.10)}.chip.time{color:#ffd486;background:rgba(200,143,45,.10)}.chip.ai{color:#c7afff;background:rgba(134,92,228,.10)}.chip.show{visibility:visible;opacity:1;animation:settleChip .24s var(--ease)}
.bottom{margin:26px 24px 0;display:flex;justify-content:space-between;align-items:center}.wave{height:42px;width:150px;display:flex;align-items:center;gap:4px;transition:.3s var(--ease)}.wave i{width:3px;height:8px;border-radius:3px;background:linear-gradient(#ff6670,#ff9a70);box-shadow:0 0 8px rgba(255,102,112,.25);animation:wave .65s ease-in-out infinite alternate}.wave i:nth-child(2n){animation-delay:.08s}.wave i:nth-child(3n){animation-delay:.16s}.phone.locked .wave{transform:scaleX(.08);opacity:.16}.caption{font-size:12px;color:#828898}.save{border:0;border-radius:15px;padding:12px 20px;font-weight:750;background:rgba(255,255,255,.07);color:#656b79;box-shadow:inset 0 0 0 1px var(--hair)}.phone.done .save{animation:unlock .42s var(--ease) forwards}
.replay{position:absolute;right:16px;top:58px;border:0;border-radius:12px;padding:8px 11px;background:rgba(255,255,255,.075);color:#d8dbe5;backdrop-filter:blur(18px);z-index:9}.flight{position:fixed;z-index:999;pointer-events:none;margin:0;white-space:nowrap;will-change:transform,width,height,border-radius,background,color,box-shadow;font-weight:650}.eraseMark:after{content:"";position:absolute;left:0;right:0;top:52%;height:1.5px;background:linear-gradient(90deg,transparent,#aeb4c6 14% 86%,transparent);transform:scaleX(0);transform-origin:left;animation:strike .12s ease-out forwards}
.legend{position:absolute;z-index:4;left:18px;right:18px;bottom:16px;display:none}.legend span{font-size:11px;color:#6f7482}
@keyframes ambient{to{transform:rotate(360deg)}}@keyframes borderDrift{from{filter:drop-shadow(0 0 7px rgba(102,173,255,.18))}to{filter:drop-shadow(0 0 14px rgba(166,129,255,.28))}}@keyframes semanticPulse{0%{background:transparent}45%{background:rgba(255,255,255,.07)}100%{background:transparent}}@keyframes spark{50%{transform:scale(1.2) rotate(12deg)}}@keyframes wave{to{height:34px}}@keyframes formWord{to{opacity:1;transform:none;filter:none}}@keyframes coreIn{to{opacity:1}}@keyframes settleChip{0%{transform:scale(.96)}60%{transform:scale(1.018)}100%{transform:none}}@keyframes unlock{0%{background:rgba(255,255,255,.07);color:#656b79}55%{transform:scale(1.035);background:#f7f8fb;color:#0a0b10;box-shadow:0 0 26px rgba(102,173,255,.22)}100%{transform:none;background:#f7f8fb;color:#0a0b10}}@keyframes strike{to{transform:scaleX(1)}}
@media(max-width:520px){.wrap{padding:0}.phone{width:100vw;height:100vh;border-radius:0}}@media(prefers-reduced-motion:reduce){.ambient,.wave i,.spark,.editor:before{animation:none!important}.flight{display:none!important}}
</style></head>
<body><div class="wrap"><main class="phone" id="phone"><div class="ambient"></div><button class="replay" onclick="replay()">↻ 重播</button><div class="status"><span>9:41</span><span>●●●　Wi‑Fi　▰</span></div><div class="head"><h1>新建 Entry</h1><p>Semantic continuity · AI 不是换一张结果，而是把信息搬到正确位置</p></div>
<section class="editor" id="editor"><div class="raw" id="raw"><span class="token filler">那个 </span><span class="token project semantic" id="srcProject">P14</span><span class="token filler"> 吧，</span><span class="token filler">我觉得</span><span class="token time semantic" id="srcTime">明天</span><span class="token filler">还是要</span><span class="token filler">把那个</span><span class="token core semantic" id="srcCore">同步的问题</span><span class="token filler">弄一下。</span></div><div class="ai-label"><span class="spark">✦</span><span id="aiText">正在理解句子结构</span></div><div class="finalrow"><span class="actionword">处理</span><span class="core-final">同步问题</span></div><div class="chipzone"><div class="chiptitle">AI 提取的结构</div><div class="chips"><span class="chip project" id="dstProject">P14 · 项目</span><span class="chip time" id="dstTime">明天 20:00</span><span class="chip ai" id="dstTag">✦ 同步</span></div></div></section>
<div class="bottom"><div><div class="wave">${'<i></i>'.repeat(24)}</div><div class="caption" id="caption">按住说 · Live Transcript</div></div><button class="save">保存</button></div></main></div>
<script>
const phone=document.getElementById('phone');const cap=document.getElementById('caption');const aiText=document.getElementById('aiText');let timers=[],flights=[];const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
function later(ms,fn){timers.push(setTimeout(fn,ms))}
function reset(){timers.forEach(clearTimeout);timers=[];flights.forEach(x=>x.remove());flights=[];phone.className='phone';document.querySelectorAll('.token').forEach(el=>{el.style.cssText='';el.classList.remove('eraseMark')});document.querySelectorAll('.chip').forEach(el=>el.classList.remove('show'));document.querySelector('.finalrow').style='';cap.textContent='按住说 · Live Transcript';aiText.textContent='正在理解句子结构'}
function collapseToken(el,delay=0){const w=el.getBoundingClientRect().width;el.style.width=w+'px';el.style.transition='none';void el.offsetWidth;later(delay,()=>{el.classList.add('eraseMark');el.animate([{opacity:1,filter:'blur(0)',transform:'translateY(0)'},{opacity:.32,filter:'blur(1px)',transform:'translateY(-1px)'}],{duration:110,easing:'ease-out',fill:'forwards'});later(115,()=>{el.style.transition='width 220ms cubic-bezier(.22,.8,.2,1),opacity 170ms ease-out,transform 170ms ease-out,margin 220ms cubic-bezier(.22,.8,.2,1)';el.style.width='0px';el.style.margin='0';el.style.opacity='0';el.style.transform='translateY(-3px) scale(.94)'})})}
function fly(source,target,kind,delay=0){later(delay,()=>{const s=source.getBoundingClientRect(),d=target.getBoundingClientRect();if(reduce){source.style.opacity='0';source.style.width='0';target.classList.add('show');return}const clone=document.createElement('span');clone.className='flight';clone.textContent=source.textContent.trim();clone.style.left=s.left+'px';clone.style.top=s.top+'px';clone.style.width=s.width+'px';clone.style.height=s.height+'px';clone.style.fontSize=getComputedStyle(source).fontSize;clone.style.lineHeight=s.height+'px';clone.style.color=getComputedStyle(source).color;clone.style.borderRadius='6px';clone.style.textAlign='center';document.body.appendChild(clone);flights.push(clone);source.style.opacity='0';const sx=d.width/s.width,sy=d.height/s.height,dx=d.left-s.left,dy=d.top-s.top;clone.animate([{transform:'translate(0,0) scale(1)',background:'rgba(255,255,255,0)',boxShadow:'0 0 0 rgba(0,0,0,0)'},{offset:.72,transform:`translate(${dx}px,${dy}px) scale(${sx},${sy})`,background:kind==='project'?'rgba(59,133,220,.10)':'rgba(200,143,45,.10)',borderRadius:'12px',boxShadow:kind==='project'?'0 0 20px rgba(102,173,255,.20)':'0 0 18px rgba(255,198,109,.15)'},{transform:`translate(${dx}px,${dy}px) scale(${sx*.985},${sy*.985})`,background:kind==='project'?'rgba(59,133,220,.10)':'rgba(200,143,45,.10)',borderRadius:'12px'}],{duration:390,easing:'cubic-bezier(.22,.8,.2,1)',fill:'forwards'}).onfinish=()=>{target.classList.add('show');clone.remove();source.style.width=s.width+'px';source.style.transition='width 220ms cubic-bezier(.22,.8,.2,1),margin 220ms cubic-bezier(.22,.8,.2,1)';requestAnimationFrame(()=>{source.style.width='0px';source.style.margin='0'})}})}
function replay(){reset();later(1250,()=>{phone.classList.add('locked');cap.textContent='松开 · 原始内容锁定'});later(1510,()=>{phone.classList.add('ai');aiText.textContent='正在识别：正文 / 项目 / 时间 / 冗词';cap.textContent='AI 接管 · 保留语义连续性'});later(1680,()=>phone.classList.add('parse'));later(1840,()=>{document.querySelectorAll('.filler').forEach((el,i)=>collapseToken(el,i*28));fly(document.getElementById('srcProject'),document.getElementById('dstProject'),'project',80);fly(document.getElementById('srcTime'),document.getElementById('dstTime'),'time',145)});later(2200,()=>{const core=document.getElementById('srcCore');const w=core.getBoundingClientRect().width;core.animate([{opacity:1},{opacity:.2,filter:'blur(2px)'},{opacity:0}],{duration:190,easing:'ease-out',fill:'forwards'}).onfinish=()=>{core.style.width=w+'px';core.style.transition='width 240ms cubic-bezier(.22,.8,.2,1)';requestAnimationFrame(()=>core.style.width='0px')};phone.classList.add('final');aiText.textContent='已整理：信息去向清晰可追踪';document.getElementById('dstTag').classList.add('show')});later(2480,()=>{phone.classList.add('done');cap.textContent='整理完成 · 等待确认保存'});later(4300,replay)}replay();
</script></body></html>`)
}