import {useEffect,useMemo,useState} from 'react';
const SB='https://reqvofpzdowwdwgmfevr.supabase.co',KEY='sb_publishable_GZqZ9q8kYWVWdpUKax9Okw_RwoQmfNw';
const timers={};
const I=[
{id:'web-plane-work-items',title:'Plane · Work Items',repo:'makeplane/plane',kind:'Task UI',image:'https://media.docs.plane.so/GitHub-readme/github-work-items.webp',note:'看高信息密度任务列表：属性很多，但主任务是否仍然清楚；适合判断 P14/P16 这类列表页该放多少信息。'},
{id:'web-plane-cycles',title:'Plane · Cycles',repo:'makeplane/plane',kind:'Planning',image:'https://media.docs.plane.so/GitHub-readme/github-cycles.webp',note:'计划、进度和时间同时出现。重点看状态和进度信息有没有抢走真正要做的事。'},
{id:'web-plane-modules',title:'Plane · Modules',repo:'makeplane/plane',kind:'Structure',image:'https://media.docs.plane.so/GitHub-readme/github-modules.webp',note:'复杂项目如何拆成模块并保持总览。看“分组”是否帮助理解，而不是制造更多层级。'},
{id:'web-plane-views',title:'Plane · Saved Views',repo:'makeplane/plane',kind:'Filtering',image:'https://media.docs.plane.so/GitHub-readme/github-views.webp',note:'筛选和自定义视图怎样存在于主界面。重点看功能很多时，控制区是否还能克制。'},
{id:'web-plane-analytics',title:'Plane · Analytics',repo:'makeplane/plane',kind:'Dashboard',image:'https://media.docs.plane.so/GitHub-readme/github-analytics.webp',note:'典型数据 Dashboard。看图表、摘要、过滤器之间的视觉主次是不是舒服。'},
{id:'web-twenty-apps',title:'Twenty · Build Apps',repo:'twentyhq/twenty',kind:'Workspace',image:'https://raw.githubusercontent.com/twentyhq/twenty/main/packages/twenty-website/public/images/readme/v2-build-apps-light.webp',note:'复杂工作区如何保持大块留白和明确分栏。看它是否有“桌面软件”感，而不是普通网页感。'},
{id:'web-twenty-layout',title:'Twenty · Custom Layouts',repo:'twentyhq/twenty',kind:'Layout',image:'https://raw.githubusercontent.com/twentyhq/twenty/main/packages/twenty-website/public/images/readme/v2-tools-light.webp',note:'同一套数据如何切换不同布局。重点看侧栏、主区域、详情区三层关系。'},
{id:'web-twenty-ai',title:'Twenty · AI Agents',repo:'twentyhq/twenty',kind:'AI UI',image:'https://raw.githubusercontent.com/twentyhq/twenty/main/packages/twenty-website/public/images/readme/v2-ai-agents-light.webp',note:'AI 被放进业务工作区，而不是独立聊天产品。看 AI 是否打扰主任务，以及它出现的位置是否合理。'},
{id:'web-twenty-crm',title:'Twenty · CRM Tools',repo:'twentyhq/twenty',kind:'Data UI',image:'https://raw.githubusercontent.com/twentyhq/twenty/main/packages/twenty-website/public/images/readme/v2-crm-tools-light.webp',note:'表格、记录、关系数据的现代 Web UI。重点看高密度信息还能否保持轻盈。'},
{id:'web-twenty-version',title:'Twenty · Version Control',repo:'twentyhq/twenty',kind:'Developer UI',image:'https://raw.githubusercontent.com/twentyhq/twenty/main/packages/twenty-website/public/images/readme/v2-version-control-light.webp',note:'技术状态、变更和操作放在同一工作区。看技术信息应该多显眼、怎样避免“工程后台味”过重。'}
];
export default function WebUI(){
 const [r,setR]=useState({}),[tab,setTab]=useState('unrated'),[kind,setKind]=useState('全部'),[q,setQ]=useState(''),[busy,setBusy]=useState('');
 useEffect(()=>{fetch(`${SB}/rest/v1/ios_ui_reference_ratings?select=*`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}}).then(x=>x.json()).then(rows=>{const m={};(rows||[]).forEach(x=>m[x.item_id]={status:x.status,custom_note:x.custom_note||''});setR(m)}).catch(()=>{})},[]);
 async function save(i,p){const n={...(r[i.id]||{}),...p};setR(v=>({...v,[i.id]:{...(v[i.id]||{}),...p}}));setBusy(i.id);await fetch(`${SB}/rest/v1/ios_ui_reference_ratings?on_conflict=item_id`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({item_id:i.id,title:i.title,repo:i.repo,kind:`Web UI / ${i.kind}`,status:n.status||'unrated',custom_note:n.custom_note||'',source:i.repo})}).catch(()=>{});setBusy('')}
 function edit(i,val){setR(v=>({...v,[i.id]:{...(v[i.id]||{}),custom_note:val}}));clearTimeout(timers[i.id]);timers[i.id]=setTimeout(()=>save(i,{custom_note:val}),700)}
 const counts=I.reduce((a,i)=>(a[r[i.id]?.status||'unrated']++,a),{unrated:0,keep:0,pass:0}),kinds=['全部',...new Set(I.map(i=>i.kind))];
 const list=useMemo(()=>I.filter(i=>{const st=r[i.id]?.status||'unrated',hay=`${i.title} ${i.repo} ${i.note} ${r[i.id]?.custom_note||''}`.toLowerCase();return(tab==='all'||st===tab)&&(kind==='全部'||i.kind===kind)&&(!q||hay.includes(q.toLowerCase()))}),[r,tab,kind,q]);
 return <main><header><small>WEB UI REFERENCE · ROUND 01</small><h1>先看真正的工作界面。</h1><p>不评品牌、不评官网。只看信息层级、导航、状态、密度和操作是否舒服。收藏 / Pass / 备注会自动保存。</p><a href="/round3">← iOS Round 03</a></header>
 <nav>{[['unrated','未评',counts.unrated],['keep','收藏',counts.keep],['pass','Pass',counts.pass],['all','全部',I.length]].map(x=><button key={x[0]} className={tab===x[0]?'on':''} onClick={()=>setTab(x[0])}><b>{x[2]}</b>{x[1]}</button>)}</nav>
 <div className="tools"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索界面或你的备注…"/><select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(x=><option key={x}>{x}</option>)}</select></div>
 <section>{list.map(i=>{const v=r[i.id]||{};return <article key={i.id} className={v.status||''}><div className="media"><img src={i.image} alt={i.title}/><span>{i.kind}</span></div><div className="body"><small>{i.repo}</small><h2>{i.title}</h2><p>{i.note}</p><textarea rows="2" placeholder="补充说明：喜欢哪里 / 为什么 Pass / 哪部分值得借鉴…" value={v.custom_note||''} onChange={e=>edit(i,e.target.value)}/><div className="acts"><button className={v.status==='keep'?'keepBtn':''} onClick={()=>save(i,{status:v.status==='keep'?'unrated':'keep'})}>收藏</button><button className={v.status==='pass'?'passBtn':''} onClick={()=>save(i,{status:v.status==='pass'?'unrated':'pass'})}>Pass</button><em>{busy===i.id?'保存中…':'自动保存'}</em></div></div></article>})}</section>
 <style jsx global>{`*{box-sizing:border-box}body{margin:0;background:#f5f5f7;color:#1d1d1f;font-family:-apple-system,BlinkMacSystemFont,sans-serif}main{max-width:1500px;margin:auto;padding:42px 30px 90px}header{max-width:900px}header small{letter-spacing:.13em;color:#6e6e73;font-weight:700}h1{font-size:clamp(42px,5vw,70px);line-height:.98;letter-spacing:-.055em;margin:12px 0 18px}header p{font-size:17px;line-height:1.55;color:#6e6e73;max-width:760px}header a{color:#6e6e73;text-decoration:none}nav{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:34px 0 14px}nav button{text-align:left;background:#fff;border:1px solid #ddd;border-radius:18px;padding:14px 16px}nav button.on{border-color:#111;box-shadow:0 0 0 1px #111}nav b{display:block;font-size:30px}.tools{display:grid;grid-template-columns:1fr 220px;gap:10px;margin-bottom:20px}.tools>*{height:46px;border:1px solid #ddd;border-radius:14px;background:#fff;padding:0 14px;font:inherit}section{display:grid;grid-template-columns:repeat(auto-fill,minmax(430px,1fr));gap:18px}article{background:#fff;border:1px solid #e1e1e5;border-radius:24px;overflow:hidden}article.keep{box-shadow:0 0 0 2px #34c75955}article.pass{opacity:.48}.media{height:300px;background:#ececef;display:flex;align-items:center;justify-content:center;position:relative;overflow:hidden}.media img{width:100%;height:100%;object-fit:contain}.media span{position:absolute;top:12px;left:12px;background:#ffffffec;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:600}.body{padding:18px}.body small{color:#86868b;font-size:11px}.body h2{font-size:21px;margin:7px 0 8px;letter-spacing:-.025em}.body p{color:#6e6e73;min-height:62px;font-size:14px;line-height:1.48}.body textarea{width:100%;min-height:44px;max-height:130px;resize:vertical;border:1px solid #dedee3;border-radius:12px;background:#fafafa;padding:10px 11px;font:inherit;font-size:13px}.body textarea:focus{background:#fff;border-color:#86868b;outline:none;min-height:72px}.acts{display:flex;gap:8px;align-items:center;margin-top:10px}.acts button{height:38px;border:1px solid #d8d8dd;border-radius:12px;background:#fff;padding:0 17px}.acts .keepBtn{background:#eaf9ee;border-color:#93d6a3}.acts .passBtn{background:#f2f2f4;border-color:#b6b6bb}.acts em{margin-left:auto;font-size:11px;font-style:normal;color:#86868b}@media(max-width:760px){main{padding:24px 16px 70px}nav{grid-template-columns:repeat(2,1fr)}.tools{grid-template-columns:1fr}section{grid-template-columns:1fr}.media{height:260px}}`}</style></main>
}